### ISSUE TITLE
Safari in-Compatibility

### ISSUE THREAD

**Issue by jacopomazzoni** [cnr-isti-vclab/openlime#15]
In some worst case scenarios on mac os devices hardware acceleration is disabled and only webgl 1 is compatible.
while the declaration detects which version of webgl is supported it later seems to use functions that are only compatible with webgl 2.

**Comment by ponchio** [comment]
WebGL2 capabilities detection has been fixed and a polyfill for ResizeObserver will be needed for older safari.
