### ISSUE TITLE
[Handling] Zoom with ctrl + wheel on PC (or ⌘ + wheel)

### ISSUE THREAD

**Issue by EloiGattet** [cnr-isti-vclab/openlime#27]
Hi!
Would it be possible to change the handling to use CTRL + wheel so when the openlime is embeded in a web page it won't stop the scrolling? 
And it could detect the scrolling but show a message a bit like here on google maps 
<img width="1409" alt="Capture d’écran, le 2022-06-13 à 13 49 53" src="https://user-images.githubusercontent.com/91476356/173347431-1d301be4-46f6-4d8a-929e-3363178f52aa.png">
(just a text message all over the canvas explaining how to zoom)

**Comment by ponchio** [comment]
Done, can be enabled setting a UIBasic property like this:

ui.controlZoomMessage = "Use control + wheel to zoom"

.openlime-overlaymsg class in css defines the look.

**Comment by EloiGattet** [comment]
Thank you very much!
