### ISSUE TITLE
Auto-animate light when idle

### ISSUE THREAD

**Issue by EloiGattet** [cnr-isti-vclab/openlime#33]
It would be very helpful to have the option to make the light move on it's own indefinitly, either when the user is idle for X seconds.
The` layer.setLight([positionX,positionY],timeinmilliseconds);` is definitly a starting point, but the rest is beyond my expertise.

And maybe and example file with a few pre-programmed trajectories/paths where we could just set size and speed would help a lot!
So we could make the light moving like a circle or an  ∞ or just going back and forth horizontally or vertically?

Anyway, thank you very much!

**Comment by ponchio** [comment]
See rti-viewer example, with a simple spinning light. Other trajectories would just need a different equation.
