### ISSUE TITLE
Limit light angle when viewing HSH basis

### ISSUE THREAD

**Issue by EloiGattet** [cnr-isti-vclab/openlime#38]
As HSH isn't bounded at the extremities is gives weird colors the moment the light are the most raking. 

Just before raking light : 
<img width="1405" alt="Capture d’écran, le 2022-10-06 à 16 04 40" src="https://user-images.githubusercontent.com/91476356/194336414-8c5dbdac-10b3-409a-af1e-9430273e75fc.png">
and just after, when the color get strange.
<img width="1407" alt="Capture d’écran, le 2022-10-06 à 16 04 30" src="https://user-images.githubusercontent.com/91476356/194337944-3a51e743-f49f-410d-963b-06301f365e79.png">

It can be unsettling for new users and give them the feeling the RTI isn't right (except it is). Would it be possible for OpenLime to limit the max angle automatically to prevent when HSH basis is detected in the info.json?

**Comment by ponchio** [comment]
There already was a limit 0.1 (in radians) for the minimal angle in raking lights.
I have added a parameter OpenLIME.HSH.minElevation that allows you to configure the minimum elevation. In radians, default is now 0.15 (up from 0.1 which was the previous default).
